### ISSUE TITLE
Is there an equivalent to prismic-reactjs' Date component?

### ISSUE THREAD

**Issue by dungle-scrubs** [prismicio/prismic-react#136]
After switching from `prismic-reactjs` to `@prismicio/react`, I don't yet see a way to render a date field.  Is this an available feature?

**Comment by angeloashmore** [comment]
Hey @dungle-scrubs,

The `Date` export from `prismic-reactjs` was just a re-export of a helper from [`@prismicio/helpers`](https://prismic.io/docs/technical-reference/prismicio-helpers). Since it is not a React-specific helper, it was removed in the new `@prismicio/react`.

You can see more details on migrating `prismic-reactjs`'s `Date()` to `@prismicio/helpers`'s `asDate()` here: https://prismic.io/docs/technologies/prismic-react-v2-migration-guide#replace-date-with-asdate

If you are upgrading your project from `prismic-reactjs` to `@prismicio/react`, I recommend going through the full Migration Guide here: https://prismic.io/docs/technologies/prismic-react-v2-migration-guide

I'm going to close this issue, but please feel free to comment here if you have any other questions. Thanks! 🙂
